---
development:
  cloud_name: hmka2ygu7
  api_key: '948725117331432'
  api_secret: CUxNWBxDGQlTwAWvGthlQxpER5E
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hmka2ygu7
  api_key: '948725117331432'
  api_secret: CUxNWBxDGQlTwAWvGthlQxpER5E
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hmka2ygu7
  api_key: '948725117331432'
  api_secret: CUxNWBxDGQlTwAWvGthlQxpER5E
  enhance_image_tag: true
  static_image_support: false
